"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Beam.py']
DATA_FILES = [('',['BeamConfig.json']),
              ('',['resources']),
              ('',['docs'])
              ]
OPTIONS = {'argv_emulation': True,
            'iconfile':'resources/icons/installer_icon/icon_MacOS.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
